# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1234, 795)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1231, 831))
        self.frame.setStyleSheet("border-image:url(:/b1.jpg)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(500, 190, 271, 111))
        self.label.setStyleSheet("font: 20pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(420, 380, 71, 41))
        self.label_2.setStyleSheet("font: 14pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(420, 470, 71, 41))
        self.label_4.setStyleSheet("font: 14pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(530, 380, 221, 41))
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(530, 470, 221, 41))
        self.plainTextEdit_2.setStyleSheet("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(520, 560, 211, 81))
        self.pushButton.setStyleSheet("font: 16pt \"Agency FB\";\n"
"border-image: url(:/b2.jpg);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.plainTextEdit_2.raise_()
        self.pushButton.raise_()
        self.plainTextEdit.raise_()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.goin) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "管理者登录"))
        self.label_2.setText(_translate("Form", "用户名："))
        self.label_4.setText(_translate("Form", "密码："))
        self.pushButton.setText(_translate("Form", "登录"))
import data.background_rc
