# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 792)
        Form.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-40, 100, 1031, 721))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video1 = QtWidgets.QLabel(self.frame)
        self.video1.setGeometry(QtCore.QRect(90, 30, 611, 491))
        self.video1.setStyleSheet("")
        self.video1.setText("")
        self.video1.setObjectName("video1")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(760, 320, 61, 41))
        self.label_3.setStyleSheet("font: 12pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.carnum = QtWidgets.QLabel(self.frame)
        self.carnum.setGeometry(QtCore.QRect(830, 330, 61, 31))
        self.carnum.setStyleSheet("font: 12pt \"Agency FB\";")
        self.carnum.setObjectName("carnum")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(800, 190, 151, 61))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(750, 150, 131, 41))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 50, 141, 51))
        self.label.setStyleSheet("font: 18pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(310, 70, 371, 31))
        self.label_2.setStyleSheet("font: 11pt \"Agency FB\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(910, 10, 71, 51))
        self.pushButton.setStyleSheet("font: 11pt \"Agency FB\";\n"
"color: rgb(170, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(230, 60, 81, 41))
        self.label_10.setStyleSheet("font: 12pt \"Agency FB\";")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.goin) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "车流量："))
        self.carnum.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "未调用"))
        self.label_4.setText(_translate("Form", "检测到车辆："))
        self.label.setText(_translate("Form", "监控"))
        self.pushButton.setText(_translate("Form", "返回"))
        self.label_10.setText(_translate("Form", "时间："))
import data.background_rc
